### ISSUE TITLE
Error while changing the #back from static to dynamic

### ISSUE THREAD

**Issue by deepraj21** [asynchronousJavascriptor/david-chang#1]
At line Shery.imageEffect("#back",{style:5,debug:true,gooey:true});

getting an error:

three.min.js:1 Scripts "build/three.js" and "build/three.min.js" are deprecated with r150+, and will be removed with r160. Please use ES Modules or alternatives: https://threejs.org/docs/index.html#manual/en/introduction/Installation
(anonymous) @ three.min.js:1
Shery.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'PlaneGeometry')
    at Module.Cr (Shery.js:2:90835)
    at script.js:1:7
   
can you please tell me how to fix it?

**Comment by deepraj21** [comment]
There was no error , my browser was blocking it.
Changed to edge and worked.
